// <auto-generated />
using System;
using EventBooking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventBooking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EventBookingDbContext))]
    [Migration("20260905060413_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventBooking.Domain.Access.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("EntraObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("entra_object_id");

                    b.Property<Guid?>("AppointmentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_type_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("EntraObjectId");

                    b.ToTable("user_role_assignment", (string)null);
                });

            modelBuilder.Entity("EventBooking.Domain.AppointmentTypes.AppointmentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<Guid?>("ManagerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("appointment_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            Code = "DAT",
                            Name = "Drug & Alcohol Testing"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000002"),
                            Code = "MED",
                            Name = "Medical Check-up"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-000000000003"),
                            Code = "UNI",
                            Name = "Uniform Fitting"
                        });
                });

            modelBuilder.Entity("EventBooking.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_id");

                    b.Property<int>("ActorType")
                        .HasColumnType("integer")
                        .HasColumnName("actor_type");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("details");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("EventBooking.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttendeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendee_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InviteId")
                        .HasColumnType("uuid")
                        .HasColumnName("invite_id");

                    b.Property<string>("ManageTokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manage_token_hash");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ManageTokenHash")
                        .IsUnique();

                    b.HasIndex("AttendeeId", "Status");

                    b.HasIndex("EventId", "Status");

                    b.ToTable("booking", (string)null);
                });

            modelBuilder.Entity("EventBooking.Domain.Attendees.Attendee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("attendee", (string)null);
                });

            modelBuilder.Entity("EventBooking.Domain.Attendees.AttendeeRequirement", b =>
                {
                    b.Property<Guid>("AttendeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendee_id");

                    b.Property<Guid>("AppointmentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_type_id");

                    b.HasKey("AttendeeId", "AppointmentTypeId");

                    b.ToTable("attendee_requirement", (string)null);
                });

            modelBuilder.Entity("EventBooking.Domain.Invites.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttendeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendee_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("AttendeeId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("Status", "ExpiresAt");

                    b.ToTable("invite", (string)null);
                });

            modelBuilder.Entity("EventBooking.Domain.Invites.InviteOption", b =>
                {
                    b.Property<Guid>("InviteId")
                        .HasColumnType("uuid")
                        .HasColumnName("invite_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.HasKey("InviteId", "EventId");

                    b.ToTable("invite_option", (string)null);
                });

            modelBuilder.Entity("EventBooking.Domain.Notifications.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttendeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendee_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TemplateName")
                        .HasColumnType("integer")
                        .HasColumnName("template_name");

                    b.HasKey("Id");

                    b.HasIndex("AttendeeId");

                    b.ToTable("email_log", (string)null);
                });

            modelBuilder.Entity("EventBooking.Domain.Settings.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("InviteExpiryDays")
                        .HasColumnType("integer")
                        .HasColumnName("invite_expiry_days");

                    b.Property<int>("MaxAutoRetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_auto_retry_count");

                    b.HasKey("Id");

                    b.ToTable("system_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InviteExpiryDays = 4,
                            MaxAutoRetryCount = 2
                        });
                });

            modelBuilder.Entity("EventBooking.Domain.Events.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("EventBooking.Domain.Events.ProposalAcceptance", b =>
                {
                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.Property<Guid>("AppointmentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_type_id");

                    b.Property<int>("Headcount")
                        .HasColumnType("integer")
                        .HasColumnName("headcount");

                    b.Property<Guid>("ManagerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_user_id");

                    b.HasKey("ProposalId", "AppointmentTypeId");

                    b.ToTable("proposal_acceptance", (string)null);
                });

            modelBuilder.Entity("EventBooking.Domain.Events.EventCapacity", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("AppointmentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_type_id");

                    b.Property<int>("RemainingCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_capacity");

                    b.Property<int>("TotalHeadcount")
                        .HasColumnType("integer")
                        .HasColumnName("total_headcount");

                    b.HasKey("EventId", "AppointmentTypeId");

                    b.ToTable("event_capacity", null, t =>
                        {
                            t.HasCheckConstraint("ck_event_capacity_within_bounds", "remaining_capacity >= 0 AND remaining_capacity <= total_headcount");
                        });
                });

            modelBuilder.Entity("EventBooking.Domain.Events.EventProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedByManagerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_manager_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("event_proposal", (string)null);
                });

            modelBuilder.Entity("EventBooking.Domain.Attendees.AttendeeRequirement", b =>
                {
                    b.HasOne("EventBooking.Domain.Attendees.Attendee", null)
                        .WithMany("Requirements")
                        .HasForeignKey("AttendeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventBooking.Domain.Invites.InviteOption", b =>
                {
                    b.HasOne("EventBooking.Domain.Invites.Invite", null)
                        .WithMany("Options")
                        .HasForeignKey("InviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventBooking.Domain.Events.Event", b =>
                {
                    b.OwnsOne("EventBooking.Domain.Events.EventWindow", "Window", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("date");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("start_time");

                            b1.HasKey("EventId");

                            b1.ToTable("event");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.Navigation("Window")
                        .IsRequired();
                });

            modelBuilder.Entity("EventBooking.Domain.Events.ProposalAcceptance", b =>
                {
                    b.HasOne("EventBooking.Domain.Events.EventProposal", null)
                        .WithMany("Acceptances")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventBooking.Domain.Events.EventCapacity", b =>
                {
                    b.HasOne("EventBooking.Domain.Events.Event", null)
                        .WithMany("Capacities")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventBooking.Domain.Events.EventProposal", b =>
                {
                    b.OwnsOne("EventBooking.Domain.Events.EventWindow", "Window", b1 =>
                        {
                            b1.Property<Guid>("EventProposalId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("date");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("start_time");

                            b1.HasKey("EventProposalId");

                            b1.ToTable("event_proposal");

                            b1.WithOwner()
                                .HasForeignKey("EventProposalId");
                        });

                    b.Navigation("Window")
                        .IsRequired();
                });

            modelBuilder.Entity("EventBooking.Domain.Attendees.Attendee", b =>
                {
                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("EventBooking.Domain.Invites.Invite", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("EventBooking.Domain.Events.Event", b =>
                {
                    b.Navigation("Capacities");
                });

            modelBuilder.Entity("EventBooking.Domain.Events.EventProposal", b =>
                {
                    b.Navigation("Acceptances");
                });
#pragma warning restore 612, 618
        }
    }
}
